services:
  
  api:
    build: .
    container_name: lms_api
    restart: always
    ports:
      - "8084:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - DB_HOST=gothub_db 
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD} # Gunakan password database Project 1
      - DB_NAME=${DB_NAME:-lms_db} # Arahkan ke database yang baru kita buat
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET:-ketikan_disini_secret_anda}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-ketikan_disini_secret_anda}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - GIN_MODE=release

    # Memberikan batasan memori agar tidak menghabiskan RAM VPS
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  default:
    external: true
    name: shared-network